version: '3.8'

services:
  vulnsense-backend:
    build: .
    container_name: vulnsense_ai_backend
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - DEBUG=False
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  vulnsense-frontend:
    build: .
    container_name: vulnsense_ai_frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://vulnsense-backend:8000/api/v1
    depends_on:
      - vulnsense-backend
    command: streamlit run app/frontend/app.py --server.port 8501 --server.address 0.0.0.0
